obstacle_extractor:
  ros__parameters:
    use_sim_time: True
    use_scan: True
    use_pcl: False
    use_pcl2: False
    use_split_and_merge: True
    cicles_from_visibles: True
    discard_converted_segments: True
    transform_coordinates: true
    min_group_points: 10
    max_group_distance: 0.1
    distance_proportion: 0.00628
    max_split_distance: 0.2
    max_merge_separation: 0.2
    max_merge_spread: 0.2
    max_circle_radius: 0.6
    radius_enlargement: 0.3
    frame_id: "map"
